### ISSUE TITLE
Publish wheels ?

### ISSUE THREAD

**Issue by neutrinoceros** [agurvich/abg_python#3]
hi @agurvich, I noticed that this gets installed in yt's CI (I assume via Firefly ?), which costs each build ~10s because no wheel is available. Cumulatively this builds up to hours of wasted CPU time. Would it be possible for you to start publishing wheels on PyPI ?

**Comment by agurvich** [comment]
in principle probably in practice i do not know how to do that. i use travis-ci to build automatically i imagine there's something I would have to add to my travis.yml?

**Comment by neutrinoceros** [comment]
I think this is the relevant doc page: https://docs.travis-ci.com/user/deployment/pypi/#uploading-different-distributions

**Comment by agurvich** [comment]
Alright, I think I did it right!

https://pypi.org/project/abg-python/#files

I see `abg_python-1.1.3-py2.py3-none-any.whl` which I think should work. Thanks for showing me how to do this!

**Comment by neutrinoceros** [comment]
Yup that works, thank you !
