### ISSUE TITLE
BUG: abg_python leaks Matplotlib configuration (side effects at import time)

### ISSUE THREAD

**Issue by neutrinoceros** [agurvich/abg_python#5]
This was discovered as the root cause of https://github.com/yt-project/yt/issues/4785, see in particular https://github.com/yt-project/yt/issues/4785#issuecomment-1912436847

Showcasing culprit lines:
https://github.com/agurvich/abg_python/blob/408f0daffb2f84130b4df096b72b77a5affdd733/src/abg_python/plot_utils.py#L26-L27

This one also has potentially undesirable side effects at import time (though it was never a problem in yt's CI, it could create issues for firefly users that could be pretty hard to debug)
https://github.com/agurvich/abg_python/blob/408f0daffb2f84130b4df096b72b77a5affdd733/src/abg_python/plot_utils.py#L5

I've tried simply dropping these three lines, which didn't break any tests from the package, so I assume they are actually disposable, but I don't know why they were added in the first place so let me know if that solution doesn't work for you.

**Comment by agurvich** [comment]
Hey @neutrinoceros , so sorry for this... These lines were put in to save me trouble setting them for copying plots into slack for my thesis advisor. God willing, these lines will never be necessary again :')

**Comment by agurvich** [comment]
merged and uploaded 1.1.5 to pypi... hopefully that gets the CI back on track. thanks @neutrinoceros !
